#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 16 11:33:34 2021

@author: desh
"""

from numpy import arange, inf

#objective function
def objective(x,y):
    return x**2.0 + y**2.0

# define range for input
r_min, r_max = -5.0,5.0

# generate grid sample from domain
sample = list()
step = 0.1
for x in arange(r_min, r_max+step,step ):
    for y in arange(r_min,r_max+step,step ):
        sample.append([x,y])
        
#evaluate sample
best_eval = inf 
best_x , best_y = None,None
for x,y in sample:
    eval = objective(x, y)
    if eval<best_eval:
        best_x= x
        best_y = y
        best_eval = eval
        
#summarise best solution
print('Best: f(%.5f,%.5f) = %.5f' % (best_x,best_y,best_eval))